- name: vars preference
  hosts: local
  connection: local
  vars: 
    name: from play level
  vars_files:
  - course.yaml
  vars_prompt:
  - name: name
    prompt: what is ur name?
    private: false
  tasks:
  - name: testing varibales sequence
    vars:
      name: from task level
    ansible.builtin.debug:
      msg: "name is : {{name}}"

      # 1.command line/args
      # 2. from prompt
      # 3.from files
      # 4.prompting
      # 5. play level 
      # 6. inventory